version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: storage_db
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U storage_user -d storage_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./fileStorageBackend/storage_backend/.env
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: storage_redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  backend:
    image: erbol92/backend
    env_file:
      - ./fileStorageBackend/storage_backend/.env
    container_name: storage_backend
    restart: unless-stopped
    command: >
      sh -c "./wait-for db:5432 --timeout=10 -- \
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn storage_backend.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120"
    volumes:
      - ./media:/app/media          # <-- МОНТИРУЕМ ЛОКАЛЬНУЮ ПАПКУ С КОМПА
      - static_volume:/app/static
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

  celery_worker:
    image: erbol92/backend
    container_name: storage_celery_worker
    restart: unless-stopped
    command: celery -A storage_backend worker --loglevel=info
    depends_on:
      - backend
      - redis
      - db
    env_file:
      - ./fileStorageBackend/storage_backend/.env
    networks:
      - app_network

  celery_beat:
    image: erbol92/backend
    container_name: storage_celery_beat
    restart: unless-stopped
    command: celery -A storage_backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - backend
      - redis
      - db
      - celery_worker
    env_file:
      - ./fileStorageBackend/storage_backend/.env
    networks:
      - app_network

  frontend:
    image: erbol92/backend
    env_file:
      - ./fileStorageBackend/storage_backend/.env
    container_name: storage_frontend
    restart: unless-stopped
    volumes:
      - ./nginx/front/nginx.conf:/etc/nginx/conf.d/default.conf
      - /opt/reb-study.ru.crt:/etc/nginx/ssl/reb-study.ru.crt
      - /opt/reb-study.ru.key:/etc/nginx/ssl/reb-study.ru.key
      - static_volume:/static
    ports:
      - "443:443"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  static_volume:

networks:
  app_network:
    driver: bridge