# Generated by Django 6.0.2 on 2026-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_file_comment_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
