# Generated by Django 6.0.2 on 2026-03-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_file_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloaded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
