# Generated by Django 6.0.2 on 2026-03-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_file_downloaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
