# Generated by Django 6.0.2 on 2026-03-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
